### ISSUE TITLE
Afterimage when moving and Over framerate

### ISSUE THREAD

**Issue by hyenachi** [googlevr/cardboard#187]
Two things on Google Cardboard XR Plugin v1.4.1 
Unity 2019.4.16f Android
Phone : Samsung s8, s10

1. I have afterimage when moving (rotation). How can i remove afterimage while head tracking?
2. I set Application.targetFrameRate 75 but frame rate is over 100. Application.targetFrameRate in unity doesn't work. How can I control framerate?

![Screenshot_20201229-173704_VR Boost](https://user-images.githubusercontent.com/5265915/103271346-5b2a8980-49fd-11eb-9df2-0d76a70768a3.jpg)

**Comment by jballoffet** [comment]
About your first question, I'm not sure what you meant by "afterimage". Perhaps you can apply changes to the head tracking algorithm to make it fit your needs. You will find its implementation within the [HeadTracker](https://github.com/googlevr/cardboard/blob/master/sdk/head_tracker.cc) and [SensorFusionEkf](https://github.com/googlevr/cardboard/blob/master/sdk/sensors/sensor_fusion_ekf.cc) classes.

About your second question, according to [here](https://forum.unity.com/threads/target-framerate-of-connected-headset.914240/), “... there is no Target Frame Rate for XR Plug-ins” and the [Application.targetFrameRate documentation](https://docs.unity3d.com/2020.2/Documentation/ScriptReference/Application-targetFrameRate.html), it seems not to work for VR.

**Comment by hyenachi** [comment]
jballoffet,
Thanks for comments.

Could you give me an advice for changes in SensorFusionEkf.cc or etc to improve fast rendering while head tracking?
I have same problem with #193, #180 , #173 , #163 and #164.
I dont think #193 is solution. Same motion blur(Afterimage) is shown.

**Comment by jballoffet** [comment]
I’d suggest you first try changing the delta time when getting the pose from the HeadTracker. You’ll see it is currently set to 50 ns in the XR plugin source code (see https://github.com/googlevr/cardboard/blob/4382d959a62196405ab75a237b5c39094a137c6e/sdk/unity/xr_unity_plugin/cardboard_xr_unity.cc#L628). Bear in mind that you’ll need to apply the [HeadTracker::GetPose() patch](https://github.com/googlevr/cardboard/issues/193#issuecomment-770036424) in order to see a different behaviour when modifying that value. In case that that doesn’t solve the problem, you can try then modifying the [Kalman filter parameters](https://github.com/googlevr/cardboard/blob/master/sdk/sensors/sensor_fusion_ekf.cc#L30-L53). Please also keep in mind that as explained in #173, there is an increased motion blur due to VR mode no longer being enabled (a feature only present in Daydream-certified phones).
