### ISSUE TITLE
 Trying to build Cardboard for iOs and get compile error on KeyboardProviderFactory

### ISSUE THREAD

**Issue by lz7cjc** [googlevr/cardboard#190]
Hi - got a showstopper here and need to understand how to fix as got a demo soon and need ios version working!	

    Last time I tried to build for iOs (normally am using android) was about 3 months ago. but now I get this error:

    Assets\GoogleVR\Scripts\Keyboard\Internal\KeyboardProviderFactory.cs(27,43): error CS0161: 'KeyboardProviderFactory.CreateKeyboardProvider(GvrKeyboard)': not all code paths return a value

    I have looked at the file but this is beyond my ability. Please help me understand how to fix this as I have got a couple of volunteers with iphones waiting to test for me and am completely stuck!

    I am using XR plug in manager on 2019.4.0f1. i used to use the VR plugin and have had a messy migration where i had to do the following to get the new system to work:

    Remove VR enabled from build setttings
    Remove the legacy Google Cardboard iOS package:
    *On Unity, go to "Window" - "Package Manager", select the "Google VR iOS" package and "uninstall"

    - Delete the file Assets/GoogleVR/Scripts/GvrCardboardHelpers.cs

    - Delete the file Assets/GoogleVR/Scripts/Keyboard/Internal/KeyboardProviders/AndroidNativeKeyboardProvider.cs

    - Open the file /Volumes/OSXData/git/masterchange/Assets/GoogleVR/Demos/Scripts/HelloVR/ObjectController.cs
    * comment line 69 -> (//GvrCardboardHelpers.Recenter();)

    thanks very much

**Comment by Mandelbrow** [comment]
Hi,

There are basically two options. The official one is to remove everything from the previous VR system. Delete the folder GoogleVR in the Assets folder. Another option is to check what the error messages says, and just address it  by comment out as few lines as possible. Most of the errors is just caused by some code blocks for the gvrEmulator for the Editor.

This line in _Assets/GoogleVR/Scripts/Controller/Internal/ControllerProviderFactory.cs_ for example:
`#if UNITY_EDITOR
            // Use the Editor controller provider which supports the controller emulator and the mouse.
            return null;    // new EditorControllerProvider(owner.emulatorConnectionMode);`

I haven't touched the GvrCardboardHelpers.cs, or anything in the Keyboard folder.

**Comment by lz7cjc** [comment]
thanks that is basically what i have done but was concerned this would mean no virtual keyboard - i can't test on iphone as don't have one!
