### ISSUE TITLE
The form is small

### ISSUE THREAD

**Issue by Git327017278** [googlevr/cardboard#200]
How to resize Windows

**Comment by hyenachi** [comment]
Take a QR code in cardboard box.

**Comment by jballoffet** [comment]
Could you please provide more information about the issue, such as:
- What form is being referred to?
- Is this taking place on Android or iOS phones?
- Is Unity being used?
- The phone and OS version being used.

**Comment by Git327017278** [comment]
<img width="1200" alt="wt34" src="https://user-images.githubusercontent.com/55872953/107191937-e4cf6d00-6a27-11eb-965a-eebd1de7d66c.png">
On Android   , in Unity ,I want to set the window size myself

**Comment by Git327017278** [comment]
@jballoffet

**Comment by jballoffet** [comment]
Thanks for the provided details. The texture size for each eye is determined upon the device parameters (lens distortion caused by the viewer lenses). You'll notice that if instead of using Cardboard Viewer v1 device parameters, you use Cardboard Viewer v2 device parameters (see image below), the size of the textures is bigger since the distortion produced by the lenses is different.

![cardboardv2](https://user-images.githubusercontent.com/20689187/116474904-7bedd900-a84f-11eb-90ee-87abd6920a05.jpg)

The distortion mesh is computed by the LensDistortion module, that you can find [here](https://github.com/googlevr/cardboard/blob/master/sdk/lens_distortion.cc).
