### ISSUE TITLE
No Stereoscopic Rendering

### ISSUE THREAD

**Issue by MikoWalteri** [googlevr/cardboard#207]
Hi,
we upgraded to Google Cardboard XR Plugin from the Unity XR Plugin. 
After switching to Google Cardboard XR we are not getting stereoscopic rendering to work. Both eyes are rendered same.

We are using Unity 2019.4 and URP

Update:

We have tried the sample scene with the latest Unity 2020 using standard renderer. Still not getting the stereoscopic rendering work properly. Both eyes are rendered from the same point. Calibration and distortion mesh is working fine, but we are not getting the same stereoscopic effect we had using Unity XR.

Does Google Cardboard for Unity actually support stereoscopic rendering by rendering both eyes from a different point? Or is Google XR using only a distortion mesh?

On the google develop site under Android NDK the sample image shows the stereoscopic rendering working correctly.

Regards,
Mikko

![c-cardboard-floating-shape-blue](https://user-images.githubusercontent.com/63716292/107604084-d4a6d000-6c69-11eb-9430-40468f1f598a.png)

![sterescopicissue](https://user-images.githubusercontent.com/63716292/107365029-33a80000-6b17-11eb-8cb8-521c0468bc71.jpg)

**Comment by maartenslaa** [comment]
I have just noticed the same thing, though my screen is wider than yours so it renders two different images but these are only shifted a little bit. Like you say the camera's are probably rendering from the same location. I'm doing some digging to see why this is. It is hard to see but it seems to be OK in the native version.

**Comment by MikoWalteri** [comment]
Thanks! Please let me know if you find anything. We haven't been able to find any solution

**Comment by maartenslaa** [comment]
I found it. It's in math_tools.cc, function `UnityXRPose CardboardTransformToUnityPose(..)` the matrix read out from the array is incorrect. It should be 12, 13, 14 instead of 3, 7, 11:

  ret.position.x = -transform[12];
  ret.position.y = -transform[13];
  ret.position.z = transform[14];
  
  This is only used in display.cc and it should not break anything else.

**Comment by maartenslaa** [comment]
@jballoffet there's an easy fix here :)

**Comment by MikoWalteri** [comment]
Thank you!!

**Comment by GrandArc** [comment]
@maartenslaa how do you apply the changes in your project? since Unity is using cardboard-xr-plugin package instead of googlevr/cardboard which has the math_tools.cc

**Comment by maartenslaa** [comment]
You can find the files of cardboard-xr-plugin package in your project tree under 'Packages' then in Runtime/Android and Runtime/iOS you will find the sdk.aar and cardboard_api.a files. These must be replaced by the version of the Cardboard SDK that you build yourself with the changes. It's not that hard. Download the cardboard repository and open the main repository folder with Android Studio, or the Cardboard.workspace in Xcode. Build the project.

For Android the files will be in folder sdk/build/outputs/aar folder. Rename the sdk-debug.aar or sdk-release.aar to sdk.aar. In Xcode find the 'Products' folder in the Xcode project Tree, right click it -> Reveal in Finder.

Replace the sdk.aar and cardboard_api.a files in the packages folder with these files. Make sure to keep the *.metadata files in place, otherwise Unity will ignore the files (this is different from the files in your assets folder).

**Comment by GrandArc** [comment]
@maartenslaa that does the magic! Thank you!
By any chance do you have the same problem like I do when if the stereoscopic rendering is fixed with this method. If you have a reticle attached to your camera, it will become like it's rendering on different positions on left and right eye, causing the reticle to look like there's 2 of them. If you had this issue as well, how do you fix them? Thanks again.

**Comment by jballoffet** [comment]
Thanks @MikoWalteri for reaching out to us, and @maartenslaa for sending the PR! The PR is currently under review and we'll reply there once it is completed. Thanks again!

**Comment by chaosemer** [comment]
This was fixed in v1.5.0.
