### ISSUE TITLE
[Question] Does this work with GL2 and ARCore? 

### ISSUE THREAD

**Issue by naiteon** [googlevr/cardboard#228]
I ask this because ARCore requires GL3, does 6dof still work when used on a gl2 project?

**Comment by jballoffet** [comment]
Thanks for reaching out. Currently, the Cardboard SDK and XR plugin supports both OpenGL ES 2 and OpenGL ES 3, which should make it compatible with ARCore (as it requires OpenGL ES 3 as you stated). Bearing this in mind, since Cardboard SDK does not provide 6DOF, in order to get it from ARCore, OpenGL ES 3 will be required. See #7 for more details.
