### ISSUE TITLE
New Input System with Cardboard not working

### ISSUE THREAD

**Issue by Pithakote** [googlevr/cardboard#230]
Hi,

I'm working on a Cardboard project for android and I cannot seem to make the New Input System work with it.
The new input system works when i build to android without using Cardboard but the new input system with the Cardboard doesn't. On the other hand, the old system works perfectly with Cardboard.

I'm not sure why this is happening, can anyone help me with this? The new input system works in the Standalone Windows build tho.

**Comment by jballoffet** [comment]
Thanks for reaching out to us. The Cardboard XR plugin currently uses the [Tracked Pose Driver from Unity XR Legacy Input Helpers](https://docs.unity3d.com/Packages/com.unity.xr.legacyinputhelpers@2.1/manual/index.html) in order to provide the current head pose to the application.

In other words, Cardboard currently doesn't support the New Input System. We are currently prioritizing what helps individual app developers the most. From that perspective, we would like to know what advantages and improvements it would bring for your apps, what use cases it would address for your apps, or what current issues in your apps it would solve. With that information we can evaluate this feature request and prioritize it accordingly.

Last but not least, I'd like to know if you have tried setting the `Active input handling` setting to `Both`.

**Comment by Pithakote** [comment]
@jballoffet  Thank you for the reply!

I am using ```Both``` in the ``` Active input handling ``` and it works just fine with the old ``` Input.GetButton() ``` and ``` old tracked pose driver  ```. 
I was asking if it would work with new input system because of the following reasons:

- Unity has decided to use the ```new action based input system``` in their future versions and I believe they've deprecated the ```old input system``` from 2020 LTS. If we were to develop a cardboard app in the future versions of Unity,  we wouldn't be able to do so.

- We'd like to have a build once, deploy anywhere project where one single project can work with the future versions of Unity, VR hardware, as well as Cardboard. 

In brief, we'd like to future proof our cardboard project because clients mostly want a mobile VR app with a few exceptions wanting the same app in VR devices like Oculus, Vive as well as mobile,  and I'm not sure if that would be possible if Cardboard cannot work with the ```new action based input system``` that Unity will be integrating in their future versions.  

Could you let me know if there are any plans in making the Cardboard work with the ```new action based input system```?

**Comment by jballoffet** [comment]
Thanks a lot @Pithakote for your detailed reply!

As said above, Cardboard SDK currently doesn't support the New Input System and there are currently no plans to support it. However, based on your reply, adding support for it may be considered in a future update. Contributions here are also welcome, in case you would like to implement it yourself.

**Comment by guneyozsan** [comment]
@jballoffet We also develop for the Oculus family, I can say it is important as it provides standardization and abstraction between input and hardware. Harder to set up but easier to develop hardware-independent apps.

**Comment by jballoffet** [comment]
Thanks @guneyozsan for providing your use case for this feature. I'll reply here in case this task gets prioritized and included in the roadmap. In the meantime, in case you would like to accelerate things, please feel free to propose the required changes via a PR. Thanks!

**Comment by yaalisri** [comment]
@jballoffet  We would also like to use New input system from unity to work with Cardboard SDK. Can you please let us know if there is any update on this feature request?

**Comment by arilow** [comment]
This issue will be solved on v1.15.0 (to be released very soon) as we have merged the changes in #345. 


After the new release is out, in order to use the new input system, you’ll need to:
1. Follow the [Input System instructions](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/manual/Installation.html) in the Unity manual.
2. Check out [this]() open PR in the [Cardboard XR Plugin](https://github.com/googlevr/cardboard-xr-plugin) repository for reference.  Cardboard XR Plugin.


Please feel free to reopen this ticket if you find any other issue regarding this topic . 

Thanks!

**Comment by xinyunh0929** [comment]
This was fixed in v1.15.0
