### ISSUE TITLE
IOS Xcode  compile error

### ISSUE THREAD

**Issue by Git327017278** [googlevr/cardboard#254]
On Unity 2020.3.5f  
How to setting Unity2020

Undefined symbols for architecture arm64:
  "_glBindVertexArray", referenced from:
      cardboard::unity::(anonymous namespace)::OpenGlEs3Renderer::RenderWidget(int, int, cardboard::unity::Renderer::WidgetParams const&) in cardboard_api.a(opengl_es3_renderer.o)
  "_glBlendFunc", referenced from:
      cardboard::unity::(anonymous namespace)::OpenGlEs2Renderer::RenderWidget(int, int, cardboard::unity::Renderer::WidgetParams const&) in cardboard_api.a(opengl_es2_renderer.o)
      cardboard::unity::(anonymous namespace)::OpenGlEs3Renderer::RenderWidget(int, int, cardboard::unity::Renderer::WidgetParams const&) in cardboard_api.a(opengl_es3_renderer.o)
  "_glBlendEquation", referenced from:
      cardboard::unity::(anonymous namespace)::OpenGlEs2Renderer::RenderWidget(int, int, cardboard::unity::Renderer::WidgetParams const&) in cardboard_api.a(opengl_es2_renderer.o)
      cardboard::unity::(anonymous namespace)::OpenGlEs3Renderer::RenderWidget(int, int, cardboard::unity::Renderer::WidgetParams const&) in cardboard_api.a(opengl_es3_renderer.o)
  "_glUniform1i", referenced from:
      cardboard::unity::(anonymous namespace)::OpenGlEs2Renderer::RenderWidget(int, int, cardboard::unity::Renderer::WidgetParams const&) in cardboard_api.a(opengl_es2_renderer.o)
      cardboard::unity::(anonymous namespace)::OpenGlEs3Renderer::RenderWidget(int, int, cardboard::unity::Renderer::WidgetParams const&) in cardboard_api.a(opengl_es3_renderer.o)
  "_glDeleteRenderbuffers", referenced from:
      cardboard::unity::(anonymous namespace)::OpenGlEs2Renderer::DestroyRenderTexture(cardboard::unity::Renderer::RenderTexture*) in cardboard_api.a(opengl_es2_renderer.o)
      cardboard::unity::(anonymous namespace)::OpenGlEs3Renderer::DestroyRenderTexture(cardboard::unity::Renderer::RenderTexture*) in

**Comment by jballoffet** [comment]
Thanks for reaching out to us. I have just tried to run Hello Cardboard using Unity 2020.3.3f1 with the latest release (v1.5.0) released yesterday and I cannot reproduce the building issue.

In order to be able to help you, I'd need to know the following:
- Are you using [Cardboard XR Plugin v1.5.0](https://github.com/googlevr/cardboard-xr-plugin/releases/tag/v1.5.0)? If not, you'll need to import it again using Unity's package manager.
- Does this issue take place with Hello Cardboard sample scene?

 For instructions about how to set up a Unity project for using Cardboard, I suggest you to take a look at the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart).

If you are still having building issues, please reach out to us again, providing a repro project and the steps required to reproduce the issue. Thanks!

**Comment by Git327017278** [comment]
using Cardboard XR Plugin v1.5.0
 This issue take place with Hello Cardboard sample scene
@jballoffet

**Comment by Git327017278** [comment]
How to setting PlayerSetting on Unity2020?

**Comment by Git327017278** [comment]
The Graphics  APIs cannot be chosen in the version 3.5f.

**Comment by Git327017278** [comment]
Xcode 12.5

**Comment by jballoffet** [comment]
Thanks for the provided information. Would you be so kind as to send me a simple Unity project where the issue can be seen and the steps required to reproduce it? It would be really helpful for debugging this issue. Thanks!

**Comment by Git327017278** [comment]
The reason for this issue was that it was not downloaded completely due to unstable network and some files were not replaced. You can solve this issue by downloading it again. @jballoffet

**Comment by tallestorange** [comment]
I tested same environment as Git327017278's.

This issue(https://github.com/googlevr/cardboard/issues/254#issue-872362908)  is happened when Cardboard_api.a dependencies is unchecked(OpenGLES, GLKit, Metal and MetalKit)
