### ISSUE TITLE
Git repo arch

### ISSUE THREAD

**Issue by Kopilov** [googlevr/cardboard#29]
Please add the .gitignore file in this project.
Thanks!

Also you can move the `sdk` project to a submodule to make it easier for using anywhere else as a dependency.

**Comment by Kopilov** [comment]
@jballoffet for your attention: I have made learning project as suggested, https://github.com/Kopilov/googlecardboard-brick
SDK (still 1.0.0) is copied to https://github.com/Kopilov/googlecardboard-sdk (not as fork because root directory is changed)

If any copies are illegal, I can remove them.

**Comment by jballoffet** [comment]
Thank you for requesting this. About the .gitignore file, we will add it to the backlog to include it in a future release. About moving the SDK to a submodule, the reason for us to have the SDK and the samples together is because it’s easier for us to maintain all together in the same repository. However, if you are interested in only an specific part within a certain repository, you could place the submodule at the root and then symlink it to the appropriate part, as mentioned here: https://gist.github.com/KingScooty/4038411.

**Comment by jballoffet** [comment]
Please consult the README.md and LICENSE files in the repository for the version you're using, where you'll find a link to the applicable terms of service and/or open source licenses that apply to the files included in that release.

**Comment by chaosemer** [comment]
A .gitignore has been added for our upcoming release.

**Comment by chaosemer** [comment]
This was fixed in v1.3.0.
