### ISSUE TITLE
How to make camera stacking on URP work with Google Cardboard

### ISSUE THREAD

**Issue by Acciai0** [googlevr/cardboard#308]
I'm trying to show some UI components on top of the scene in order to make them always visible regardless of their position in space. In order to do this, I'm using the camera stacking feature, but it causes issue both on Android and iOS. 
On iOS (specifically metal) the overlay camera is only rendered for the right eye. I've seen some forum topics suggesting to deactivate post processing, but I've never activated it in the first place and now I find myself without ideas.
On Android it straight down doesn't work. The scene is loaded (i can tell from the audio), but the "made with unity" splash screen doesn't disappear making it for all uses and purposes, broken. Removing the UI camera makes the scene work as expected again. What am I doing wrong?

Additional Info:
Unity version 2020.3.20f1 - URP project, Google Cardboard version 1.9,0

The main camera is exactly equal to the one in the sample scene, the UI camera is set as overlay and set as first in the stack of the main camera.

**Comment by Acciai0** [comment]
UPDATE: It seems to be related to the Rendering method being set by default to Multi-Pass and not single-pass, but using theGoogle Cardboard XR SDK there is no option in editor to change this. Is it supported? Where can I use change it?

**Comment by arilow** [comment]
Thanks  @Acciai0 for reaching out to us. Unfortunately the Cardboard SDK and XR Plugin currently does not support single pass rendering. 


Issue #142 is currently tracking the feature request for Single Pass support.


About URP, we have recently detected issues when using an XR Plugin with URP and linear color space. Since the behavior differs across different Unity versions, this issue has been reported to Unity. See #199 for further details about this issue.
