### ISSUE TITLE
Older version

### ISSUE THREAD

**Issue by MusemoDeveloper** [googlevr/cardboard#327]
Hello there, I need an older version of plugin. How can I get  git link  (for example of version 1.5)  to add into unity?

**Comment by arilow** [comment]
Thanks @MusemoDeveloper for reaching out to us!
In order to import older versions of the Cardboard XR Plugin from Unity you need to use a git URL as the following:
 
```
https://github.com/googlevr/cardboard-xr-plugin.git#vx.x.x
```
 
Therefore, if you want to import Cardboard XR Plugin v1.5.0, the URL would be:
```
https://github.com/googlevr/cardboard-xr-plugin.git#v1.5.0
```
 
Please take a look at the [Targeting a specific revision](https://docs.unity3d.com/Manual/upm-git.html#revision) section in the Unity documentation for further information about how to manage versioning with Git. Thanks!

**Comment by MusemoDeveloper** [comment]
Thnks, it works
