### ISSUE TITLE
On some versions of Unity 2019.3, XR mode will not be entered unless Project Settings > Player > Splash Image > Show Splash Screen is unchecked.

### ISSUE THREAD

**Issue by chaosemer** [googlevr/cardboard#35]
Note: this option is available in Unity Plus and Unity Pro.

**Comment by Bubu-Shawn** [comment]
Hi @chaosemer 
I tried to import the SDK into my project according to the steps in [Quickstart for Google Cardboard for Unity](https://developers.google.com/cardboard/develop/unity/quickstart) but I can't find **Google Cardboard XR Plugin** for Unity in my package. I'm using Unity Personal. Is this issue related to this?

**Comment by Bubu-Shawn** [comment]
Hi @chaosemer is there any timeline that this will be fixed?

**Comment by chaosemer** [comment]
This is certainly near the top of our list as it prevents a significant amount of developers from using the Cardboard XR Plugin. For context, the other things near the top being discussed are other major usage blockers such as Metal support and open sourcing the native parts of the plugin.

We haven't done a prioritization pass yet, so we don't yet have a firm commitment to the exact order we'll hit those major usage blockers.

**Comment by Bubu-Shawn** [comment]
@chaosemer sorry to ask this question which is not quite related to this issue.

I managed to run HelloCardboard on iOS but it's not rendered in stereoscopic and even i have scanned my cardboard QR code and nothing happens. Is there any guide on how to make stereoscopic rendering somewhere?
![IMG_0170](https://user-images.githubusercontent.com/5226787/82401967-cc7c8400-9a8d-11ea-8140-a11070f866ae.PNG)

**Comment by synthercat** [comment]
Could you please make more clear what exactly do you mean by "On some versions"??? The quick start does mention 2019.3.12 or later as software requirement. Ι verify that 2019.3.12 & 2019.3.13 do not work. 
Also let me politely add some notes about that quick start guide (by the way, is the the right place to comment on that documentation?)
1. You should add minimum Android API (I am guessing 21)
2. "Select both ARMv7 and ARM64" I think you means "Select the architecture you want" 

Thank you for supporting this great platform!

**Comment by evilstef** [comment]
Is there a workaround for this issue? Like disable Initialize XR on Startup and initialize it manually?

**Comment by ArthurAtlantico** [comment]
I managed to get it working with Unity Personal using these settings:

Player->XR Settings:
Under Deprecated Settings...
Check Virtual Reality Supported
Add None to Virtual Reality SDKs

XR Plugin-in Management:
On the Android tab...
Check Initialize XR on Startup
Check Cardboard XR Plugin

Please note that leaving Virtual Reality Supported uncheck might lead to a black screen with the default carboard UI. This shows up before the splash screen and you'll get stuck in it. Unchecking Initialize XR on startup under XR Plugin-in Management leads to a crash right after the Unity logo. So yes, you'll have to mix updated stuff with deprecated stuff. 

I am using Unity 2019.3.14.f1

**Comment by CedoSnr** [comment]
> I managed to get it working with Unity Personal using these settings:
> 
> Player->XR Settings:
> Under Deprecated Settings...
> Check Virtual Reality Supported
> Add None to Virtual Reality SDKs
> 
> XR Plugin-in Management:
> On the Android tab...
> Check Initialize XR on Startup
> Check Cardboard XR Plugin
> 
> Please note that leaving Virtual Reality Supported uncheck might lead to a black screen with the default carboard UI. This shows up before the splash screen and you'll get stuck in it. Unchecking Initialize XR on startup under XR Plugin-in Management leads to a crash right after the Unity logo. So yes, you'll have to mix updated stuff with deprecated stuff.
> 
> I am using Unity 2019.3.14.f1

This didn't work for me. I'm still getting the black screen. Did you happen to change any other settings too?

**Comment by ArthurAtlantico** [comment]
Did you get just a black screen and nothing else? Can you see the cardboard UI?

**Comment by ezefranca** [comment]
> Did you get just a black screen and nothing else? Can you see the cardboard UI?

Looks like you cannot use this plugin without a Unity Pro version. I got the same black screen here.

**Comment by ws18** [comment]
> 
> 
> I managed to get it working with Unity Personal using these settings:
> 
> Player->XR Settings:
> Under Deprecated Settings...
> Check Virtual Reality Supported
> Add None to Virtual Reality SDKs
> 
> XR Plugin-in Management:
> On the Android tab...
> Check Initialize XR on Startup
> Check Cardboard XR Plugin
> 
> Please note that leaving Virtual Reality Supported uncheck might lead to a black screen with the default carboard UI. This shows up before the splash screen and you'll get stuck in it. Unchecking Initialize XR on startup under XR Plugin-in Management leads to a crash right after the Unity logo. So yes, you'll have to mix updated stuff with deprecated stuff.
> 
> I am using Unity 2019.3.14.f1

Looks like I'm getting somewhere thanks to this. I'm using the example provided by Google, when I launch the app it asks me for a QR code which I don't have at the moment, so I skip it, and all I see is this: https://imgur.com/a/3yja3Jx is it normal? Shouldn't I see the scene with the HelloCardboard scene?

**Comment by kismeter** [comment]
> > I managed to get it working with Unity Personal using these settings:
> > Player->XR Settings:
> > Under Deprecated Settings...
> > Check Virtual Reality Supported
> > Add None to Virtual Reality SDKs
> > XR Plugin-in Management:
> > On the Android tab...
> > Check Initialize XR on Startup
> > Check Cardboard XR Plugin
> > Please note that leaving Virtual Reality Supported uncheck might lead to a black screen with the default carboard UI. This shows up before the splash screen and you'll get stuck in it. Unchecking Initialize XR on startup under XR Plugin-in Management leads to a crash right after the Unity logo. So yes, you'll have to mix updated stuff with deprecated stuff.
> > I am using Unity 2019.3.14.f1
> 
> This didn't work for me. I'm still getting the black screen. Did you happen to change any other settings too?

It didn't work for me. I see the black screen with cardboard ui. none content appear

**Comment by CedoSnr** [comment]
> Did you get just a black screen and nothing else? Can you see the cardboard UI?

I can see the cardboard UI, although none of it functions (settings & x buttons, stereoscopic screen split). Other than that everything is black.

**Comment by ArthurAtlantico** [comment]
Did you all follow the tutorial steps first? If not, then try it first. I'm not sure if all these settings matter, but my project is configured like this:

**Other Settings:**
- Aspect Ratio Mode: Landscape Left
- Graphics API: OpenGLES2 (only this)
- Minimum API Level = Nougat (7.0)
- Script Backend: Mono (I tried both Mono and IL2CPP and both work. I'm using Mono to test because the compilation is faster)
- Internet access: require
- Managed Stripping Level: disabled

**Publishing Settings**
- Custom main gradle template is checked. I set the gradle file just like the tutorial.

**XR Settings** 
- Virtual Reality Checked. Add None do SDK and nothing else 

If you don't want to check Initialize XR on Startup, you have to call these right before you need to use VR:

`
XRGeneralSettings.Instance.Manager.InitializeLoaderSync();
XRGeneralSettings.Instance.Manager.StartSubsystems();
`

Also put the HelloCardboard scene first. You should see the Unity logo in VR mode then the demo. If you don't see the logo, try using logcat to see what's going on. You can do this using Android Studio or checking development build and scripting debugging before you build your apk. The logs should appear in the console tab if you select AndroidPlayer instead of Editor.

When I had this problem of seeing a black screen after the logo, I found out that it happened because my home screen scene had a bunch of UI elements and they were inside a Canvas parent in overlay mode. 

Not sure if related to the issue but I'm using Vuforia as well. Tried to mix Cardboard and ARCore as well, but they don't run together because one requires OpenGLES3 and the other OpenGLES2, so I'm using only Cardboard right now.

Here is a proof of cardboard running on my phone. Note that the X and gear icons can't be seen, but if I touch the places where they should be, they work. Minor issue.
![cardboard_works](https://user-images.githubusercontent.com/63819531/82665599-8436a080-9c0a-11ea-9d96-88ff128cbcac.jpg)

**Comment by ArthurAtlantico** [comment]
If you check Initialize XR on Startup and everything works fine, you should see this:
![unity_logo_vr](https://user-images.githubusercontent.com/63819531/82666485-6a965880-9c0c-11ea-8c13-3c3befb76989.jpg)

Note that the icons show up. When I initialize manually, the icons disappear.

**Comment by CedoSnr** [comment]
> Did you all follow the tutorial steps first? If not, then try it first. I'm not sure if all these settings matter, but my project is configured like this:
> 
> **Other Settings:**
> 
> ......

Thanks for the detailed response! 

I managed to get it working. I realised I glossed over one part of your instructions: "Add None to Virtual Reality SDKs". I think I had just assumed this meant don't add anything. When I loaded up the Unity project again today it gave me an error related to this.

Otherwise, all my settings were the same as in the tutorial.

Well done for finding this solution, thanks!

**Comment by evilstef** [comment]
Works fine. Thx.

**Comment by jballoffet** [comment]
Thank you @synthercat for reporting this. We will update the documentation to add more clarity to this step soon.

**Comment by Bubu-Shawn** [comment]
> > Did you get just a black screen and nothing else? Can you see the cardboard UI?
> 
> I can see the cardboard UI, although none of it functions (settings & x buttons, stereoscopic screen split). Other than that everything is black.

I see the cardboard UI with black screen too. And both settings and x button are working on iPhone XR, iOS 13.3. Did anyone managed to get it worked on iPhone?

**Comment by jballoffet** [comment]
Splash screen integration with XR mode was solved by Unity on 2019.3.15f1 or later, including all versions 2019.4 and 2020.1. See [here](https://unity3d.com/unity/whats-new/2019.3.15) for more details.

**Comment by RJSD3V** [comment]
How would you test an application in play mode itself. Im getting a static view of the camera view. (Can't look around on running the project)
