### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by xslom** [googlevr/cardboard#356]
I have been trying to build for a couple of days and i get the same issue every time 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Asus\.gradle\caches\transforms-2\files-2.1\11318262f7bf19b0e02219276a0cab65\GfxPluginCardboard\AndroidManifest.xml:23:9-27:66: AAPT: error: resource style/Theme.AppCompat.NoActionBar (aka com.DefaultCompany.AndroidG:style/Theme.AppCompat.NoActionBar) not found.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Please Help

**Comment by arilow** [comment]
Thanks for reaching out  to us @xslom! 


I was able to get the same error as you by skipping the [Publishing Settings](https://developers.google.com/cardboard/develop/unity/quickstart#publishing_settings) instructions in the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart).


You would need to go to `File > Build Settings > Player Settings > Publishing Settings` and select:
-  `Custom Main Gradle Template`
-  `Custom Gradle Properties Template`. 


When you do that, 2 files will be created under `{YOUR_PROJECT_PATH}/Assets/Plugins/Android/`, `mainTemplate.gradle` and `gradleTemplate.properties. You will need to paste the proper configuration into them according to the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart#publishing_settings).


In case this does not solve your issue, please reopen this ticket sharing with us:
- The required steps to expose the issue.
- The Cardboard XR Plugin version being used.
- Unity version.
- A simple Unity project where this issue is depicted would also be very helpful.


 Thanks!
