### ISSUE TITLE
Flip/Mirror camera view

### ISSUE THREAD

**Issue by schwrzerik** [googlevr/cardboard#358]
I am trying to make an app for a vr/ar headset where the phone is mounted with the screen facing away from the user so the view/camera needs to be flipped to be correct but I can't get the camera view to be flipped on all axis. It always corrects the view so it's normal again.

**Comment by arilow** [comment]
Thanks @schwrzerik for reporting this issue. In order to allow us to reproduce this, I would ask if you could please provide:
- The required steps to expose the issue. How are you trying to flip the camera?
- Are you using Unity? Which version?
- Is this issue reproducible with the HelloCardboard sample scene?
- A simple Unity project where this issue is depicted would also be very helpful.


Thanks!
