### ISSUE TITLE
How to remove the back and settings button?

### ISSUE THREAD

**Issue by Bawenang** [googlevr/cardboard#366]
Hi, a client of mine asked me to remove the buttons in the VR. I browsed the internet (and here specifically) and I found out that they are actually non-optional so we can't do that. Someone suggested decompiling a java file in the aar, disable them from there and then recompile it again. Is there any simpler way to do this? And also, why do you make it non-optional to begin with? Since I noticed lots of other people also complained about the same thing as I did.

Oh yeah, BTW, the UIs also may not work as you might want them to work. I tried creating a new scene but I forgot to include the `VrModeController` component in it so the buttons are still there but they didn't do anything. So I was thinking, you should couple the buttons with that script.

**Comment by arilow** [comment]
Thanks for reaching out to us @Bawenang! 


The code used  to add the widgets on the Unity side is in [XRLoader.cs](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Runtime/XRLoader.cs).


In [`RecalculateRectangles`](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Runtime/XRLoader.cs#L151), you can call [`CardboardUnity_setWidgetCount()`](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Runtime/XRLoader.cs#L160) passing 0 instead of 3 and erasing the following lines that add the widgets.


The complete method should look like this in your case:
```
internal static void RecalculateRectangles(Rect renderingArea)
        {
            CardboardUnity_setScreenParams(
                    (int)Screen.width, (int)Screen.height, (int)renderingArea.x,
                    (int)renderingArea.y, (int)renderingArea.width, (int)renderingArea.height);


            CardboardUnity_setWidgetCount(0);
        }
```


Then you can follow the calls to [`IsCloseButtonPressed`](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Runtime/Api.cs#L53) and [`IsGearButtonPressed`](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Runtime/Api.cs#L72) to take out their functionality.


`VrModeController` is just a sample script that shows how to turn VR on and off. It also works as a guide to create your own application using the Cardboard XR plugin. On the other hand, the widgets are part of the XR Plugin itself and, as such, they are located within the XR Plugin package.


Please let us know if you need additional help regarding this ticket.
Thanks!

**Comment by Bawenang** [comment]
Hi, thank you for the reply. I'll try it. Thanks again.

**Comment by prakyath-07** [comment]
It works
