### ISSUE TITLE
Cardboard 3.2 crashing when launching device cofiguration

### ISSUE THREAD

**Issue by OmegaMule** [googlevr/cardboard#367]
### SPECIFIC ISSUE ENCOUNTERED
Crash when launching Cardboard's device configuration intent from another Cardboard app. This crash doesn't happen on previous Cardboard App versions.

### SMARTPHONE (please complete the following information):
Locally reproduced on Galaxy S4. Externally reported by users on multiple devices.
Android 4.4, Android 6, Android 10 etc..

### STEPS TO REPRODUCE THE ISSUE
Open a 3rd party Cardboard app, which was not started via Cardboard launcher. When in VR, click on configuration button. The app will crash due to permissions.

### EXPECTED BEHAVIOR
Apps will not crash.

### VERSIONS USED
Unity's Cardboard package version 2.0.0

**If you are using Cardboard XR Plugin:**
Unity 2019.4.28f1

### ADDITIONAL CONTEXT
java.lang.SecurityException: Permission Denial: starting Intent { act=com.google.vrtoolkit.cardboard.CONFIGURE cmp=com.google.samples.apps.cardboarddemo/com.google.vr.cardboard.paperscope.carton.Settings } (pid=3968, uid=10398) not exported from uid 10404

Probably caused by the "export=true" missing in Cardboard's app manifest?

**Comment by arilow** [comment]
Thanks for reaching out to us @OmegaMule! 


Given that this repository is meant to maintain only the Cardboard SDK and the Cardboard XR Plugin, I am afraid I have to close this ticket as it is not related to the mentioned packages.


In order to send feedback to the Android App team, you can do it by pressing the “Help and Feedback” buttons in the 3 dots menu.


Thanks!
