### ISSUE TITLE
¿Which Unity version is the most stable with cardboard-xr-plugin?

### ISSUE THREAD

**Issue by sateyr** [googlevr/cardboard#373]
Hi,
i need to update this project to upload a new version on Google Play and Apple Store:
 - Unity 2019.4.4.12f1
 - Google Cardboard XR Plugin 1.2.0
 - Minimum API Level: Android 4.4 ´KitKat´ (API Level 19)
 - Target API Level: 31
 - Built-it Render Pipeline

¿Could anyone tell me which Unity Version can be a better option to update the project? (Less bugs, more stability, etc )

Thanks in advance ^^

PD (I dont know how to change the label to "question")

**Comment by arilow** [comment]
Thanks @sateyr for reaching out to us! 


In order to know which Unity versions are supported by the Cardboard XR Plugin, you can take a look at “[Set up your development environment](https://developers.google.com/cardboard/develop/unity/quickstart#set_up_your_development_environment)” in the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart).


We use Unity LTS versions to test the Hello Cardboard Sample App. 
Other info:
- Minimum API level: From Cardboard SDK v1.12 on, the minimum API level is 24 due to Vulkan support. If you need a lower API level, PTAL at the documentation [here](https://github.com/googlevr/cardboard/blob/master/sdk/build.gradle#L10).


- Target API level: we suggest using the current SDK target API level or higher (see[ https://github.com/googlevr/cardboard/blob/master/sdk/build.gradle#L19](https://github.com/googlevr/cardboard/blob/master/sdk/build.gradle#L19)). It is currently 31.


- There have been some changes in the API since v1.2 so you might need to add some changes to your code too. 


Please let us know if you need further help regarding this.
Thanks!

**Comment by andypoly** [comment]
It seems to need 2020 now - but I need a back fix for a 2019 LTS project also.
Is there a file I can copy to fix iPhone 14 VR?

**Comment by sateyr** [comment]
> Thanks @sateyr for reaching out to us!
> 
> In order to know which Unity versions are supported by the Cardboard XR Plugin, you can take a look at “[Set up your development environment](https://developers.google.com/cardboard/develop/unity/quickstart#set_up_your_development_environment)” in the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart).
> 
> We use Unity LTS versions to test the Hello Cardboard Sample App. Other info:
> 
> * Minimum API level: From Cardboard SDK v1.12 on, the minimum API level is 24 due to Vulkan support. If you need a lower API level, PTAL at the documentation [here](https://github.com/googlevr/cardboard/blob/master/sdk/build.gradle#L10).
> * Target API level: we suggest using the current SDK target API level or higher (see[ https://github.com/googlevr/cardboard/blob/master/sdk/build.gradle#L19](https://github.com/googlevr/cardboard/blob/master/sdk/build.gradle#L19)). It is currently 31.
> * There have been some changes in the API since v1.2 so you might need to add some changes to your code too.
> 
> Please let us know if you need further help regarding this. Thanks!

I have finally upgraded from the 2019 to the 2021 LTS and it´s working well. I have had less errors/bugs that when i tried to update to the 2020 LTS a year ago.

Thanks @arilow ^^

**Comment by arilow** [comment]
@andypoly, the technical specs for iPhone 14 variants have been added in Cardboard SDK v1.18.0 so we recommend using that one.


On the other hand, the minimum Unity version supported now is 2020.3 since 2019 has been deprecated. You can try to use it anyways but we can not ensure that it will work properly since it is no longer supported by Cardboard.


In case it helps, the iPhone 14 variants specs have been added to [screen_params.mm](https://github.com/googlevr/cardboard/blob/master/sdk/screen_params/ios/screen_params.mm).


On the [last commit](https://github.com/googlevr/cardboard/commit/2c317e54173d4a47eb75b19135cffdc5ff35b883#diff-df9ac93ac73eb84593606cffc684fb9640e704a3e6fda96ca9cf42340a81c78a) you can see the changes we added to that file in order to support iPhone 14 devices.


I am closing this ticket as the original issue was resolved. Feel free to create a new ticket if you need further help.


Thanks!
