### ISSUE TITLE
Run Google Cardboard XR for Unity Demo "Hello Cardboard" ,it Crashed

### ISSUE THREAD

**Issue by zhaochunping123** [googlevr/cardboard#381]
I’m use google cardboard XR for Unity demo “Hello Cardboard” , the demo where I download form “https://github.com/googlevr/cardboard-xr-plugin.git”.
And then I set up my development  environment due to your official guide as “https://developers.google.com/cardboard/develop/unity/quickstart#recommendations-link”, then I build it and run will Galaxy s8+ Mobile.
But when I run the app, it crashed ,and no error . the log end with
 "11-08 16:52:54.691 28817 28856 D Unity   : Sensor :        Accelerometer ( 1) ; 0.002396 / 0.00s ; LSM6DSL Accelerometer / STMicroelectronics
11-08 16:52:54.691 28817 28856 D Unity   : Choreographer available: Enabling VSYNC timing
11-08 16:52:54.717 28817 28856 I Unity   : [XR] [CardboardXrDisplayProvider]: Initializes Cardboard API.
"
My Unity version is 2020.3.38

**Comment by zhaochunping123** [comment]
Anyone know why？

**Comment by zhaochunping123** [comment]
when I don't check the option of   ProjectSetting/XRPlugin-inManager/cardboard XR plugin, the carsh not happened
![1](https://user-images.githubusercontent.com/63340937/201250986-e20b4632-2dec-4981-a865-7d5a610e9f6f.png)

**Comment by orenccl** [comment]
same problem

**Comment by arilow** [comment]
Thanks @zhaochunping123 for reaching out to us! In order to allow us to reproduce this issue, could you please provide:
- The Cardboard XR Plugin version being used.
- The required steps to expose the issue. Even if you are following the quickstart, please write the steps you are doing. So we can check any differences there might be.
- Device model and fingerprint. You can get the fingerprint using adb with the following command:
```
adb shell getprop ro.build.fingerprint
```
- Graphics API being used (OpenGL 2, OpenGL 3 or Vulkan).
- A simple Unity project where this issue is depicted would also be very helpful.

Thanks!

**Comment by zhaochunping123** [comment]
>hi arilow :
 My cardboard XR Plugin version is 1.18.0, and my build step is :
 1. Import XR SDK to empty Project, choose "HelloCardboard" to open sample Scene
 2. Switch Platform to Android
 3. Navigate to Project Settings > Player > Resolution and Presentation
      1) Set the Default Orientation to Landscape Left or Landscape Right.
       2)Disable Optimized Frame Pacing
4. Navigate to Project Settings > Player > Other Settings.
       **1) Graphics API  OpenGL2**
       2）MInimum API Level to Android 7.0
       3）Scripting Backend in IL2CPP
       4) choosing ARMv7, ARM64, in Target Architectures
       5)Select Require in Internet Access.
5. Publishing Settings/Navigate to Project Settings > Player > Publishing Settings
        1) select Custom Main Gradle Template and Custom Gradle Properties Template
        2) add the following lines to the dependencies section of Assets/Plugins/Android/mainTemplate.gradle:
                implementation 'com.android.support:appcompat-v7:28.0.0'
                implementation 'com.android.support:support-v4:28.0.0'
                implementation 'com.google.android.gms:play-services-vision:15.0.2'
                implementation 'com.google.protobuf:protobuf-lite:3.0.0'
        3)add the following lines to Assets/Plugins/Android/gradleTemplate.properties:
              android.enableJetifier=true
              android.useAndroidX=true
6. XR Plug-in Management Settings ：select Cardboard XR Plugin under Plug-in Providers.
7.  Build the apk

PS: my  device model is Galaxy s8+ ， 
      fingerprint : samsung/dream2qltezc/dream2qltechn:9/PPR1.180610.011/G9550ZCS6DUD1:user/release-keys

**Comment by zhaochunping123** [comment]
> same problem

have your problem resolved?

**Comment by zhaochunping123** [comment]
> Thanks @zhaochunping123 for reaching out to us! In order to allow us to reproduce this issue, could you please provide:
> 
> * The Cardboard XR Plugin version being used.
> * The required steps to expose the issue. Even if you are following the quickstart, please write the steps you are doing. So we can check any differences there might be.
> * Device model and fingerprint. You can get the fingerprint using adb with the following command:
> 
> ```
> adb shell getprop ro.build.fingerprint
> ```
> 
> * Graphics API being used (OpenGL 2, OpenGL 3 or Vulkan).
> * A simple Unity project where this issue is depicted wou

**Comment by arilow** [comment]
Thanks a lot for the provided information @zhaochunping123 and sorry for the delay!

I was able to reproduce the issue you are describing. In order to fix it, I had to update the dependencies in `Assets/Plugins/Android/mainTemplate.gradle` for those in the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart#publishing_settings):
```
  implementation 'androidx.appcompat:appcompat:1.4.2'
  implementation 'com.google.android.gms:play-services-vision:20.1.3'
  implementation 'com.google.android.material:material:1.6.1'
  implementation 'com.google.protobuf:protobuf-javalite:3.19.4'
```


Please take into account that with these dependencies, you will have to go to `Project Settings > Player > Other Settings` and Select `API level 31` or higher in `Target API Level`.


I am closing this issue as it should be fixed. Feel free to reopen it if that’s not the case.
Thanks!
