### ISSUE TITLE
Cant import from link

### ISSUE THREAD

**Issue by TobitheToast** [googlevr/cardboard#383]
I wanted to add this plugin to my package manager with this link:
https://github.com/googlevr/cardboard-xr-plugin.git

I go under Package Manager/Add package from git url
paste the link and hit "add", but nothing is getting installed.
How can I fix this? (Please a simple answer my english is not that good and I am pretty young)

**Comment by zhaochunping123** [comment]
you should install git first .

**Comment by arilow** [comment]
Thanks @TobitheToast for reaching out to us!


As zhaochunping123 stated, you need to install git in order to import a unity package from a github URL.


If you don’t want to install git, you can:
- Download the repo code ([cardboard-xr-plugin](https://github.com/googlevr/cardboard-xr-plugin)) as a ZIP:
<img width="300" alt="Screen Shot 2022-11-11 at 10 28 54" src="https://user-images.githubusercontent.com/43258762/201366670-0fd2792a-887b-4094-a771-83dbad1c2c4c.png">

- Unzip.
- In your Unity project, go to the window manager.
- Add package from disk.
- Go where you unzipped the XR plugin and select the file called [package.json](https://github.com/googlevr/cardboard-xr-plugin/blob/master/package.json).
- After the package is added, you can keep going with the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart)


Let us know how that goes!
