### ISSUE TITLE
How are the Unity cardboard XR plugin and GVRCardboard related?

### ISSUE THREAD

**Issue by lexar** [googlevr/cardboard#43]
I guess I'm missing something. I have a Unity 2017 project with GVRCardboard SDK 1.130.1 which I would like to "upgrade" to Unity 2019 and the cardboard XR plugin. 
I deleted the GoogleVR plugin in the project and enabled the XR plugin.
Now I get build errors on lines referencing GVRCardboard ie 
GvrUnitySdkVersion.GVR_SDK_VERSION
GvrCardboardHelpers.Recenter()

I was under the impression that the cardboard XR plugin would be the latest release of the  GVRUnity SDK, is that wrong? 
Because the API at https://developers.google.com/cardboard/reference/unity does not mention anything of the old GVRCardboard Unity API and I can't find any reference within Unity, too.
Is the cardboard XR plugin a completely different thing?

What is the recommended strategy to convert an old project?

Thanks, lexar

**Comment by friggasaint** [comment]
To my understanding it is a different since it uses the XR-Plugin Framework which is new in Unity compared to built-in XR (Player >XR Settings), that is already labeled deprecated on Unity 2019.3.
As far as I can tell also some functionalities in the cardboard plugin compared to the SDK are missing.
As for the strategy, I'm trying to find out myself.

Regards.

**Comment by jballoffet** [comment]
As @friggasaint said, Cardboard XR Plugin uses the Unity XR Plugin framework instead of the deprecated built-in GVR integration. Unity will be removing support for the deprecated GVR integration in a future version of Unity so we encourage you to either stick to an LTS version of Unity that supports it or port your app to the Cardboard XR Plugin. See [Unity's blogpost](https://blogs.unity3d.com/2020/01/24/unity-xr-platform-updates/) for more details.

Cardboard has a different API from GVR and its documentation can be found [here](https://developers.google.com/cardboard/reference/unity). For more differences about Cardboard and GVR, please see #6.

**Comment by jeff-rey-unity** [comment]
what would you call to replace GvrCardboardHelpers.Recenter() in the new xr plugin?

**Comment by AGamlin** [comment]
> what would you call to replace GvrCardboardHelpers.Recenter() in the new xr plugin?

I too would like to know what the plan for Recenter() is. 

Right now every time my user opens the app, they have to rotate some random rotation away from the position they were when they started the app.

**Comment by jballoffet** [comment]
Sorry for the delay here, about the recentering API, I recommend you take a look at #242. We're still in the process of migrating those changes internally, but you should be able to patch the changes locally and use the feature. Hope this helps.

**Comment by AGamlin** [comment]
Thankyou very much. I lookforward to having a go.

best,

Adam

**Comment by AGamlin** [comment]
> Sorry for the delay here, about the recentering API, I recommend you take a look at #242. We're still in the process of migrating those changes internally, but you should be able to patch the changes locally and use the feature. Hope this helps.

@jballoffet Since we access the package through Unity differently now, by entering "https://github.com/googlevr/cardboard-xr-plugin.git" into the package manager, im not sure if or how we can do that locally. If there is a way to install the recenter branch as the package to the project, would you mind explaining how?

**Comment by jballoffet** [comment]
@AGamlin, just a heads up that release v1.6.0 is out now, including the recentering feature.

**Comment by AGamlin** [comment]
Thanks again for your efforts, my project is already updated with 1.6.0

**Comment by jballoffet** [comment]
I'm closing this question given that the [Recenter API entry](https://developers.google.com/cardboard/reference/unity/class/Google/XR/Cardboard/Api#recenter) has been added in release v1.6.0.
