### ISSUE TITLE
Camera rotation too slow

### ISSUE THREAD

**Issue by IrvingMacias-Amco** [googlevr/cardboard#450]
### SPECIFIC ISSUE ENCOUNTERED
I integrated the asset, it compiles, but the camera moves too slow, and I think only in vertical, because I don´t see if the camera moves in horizontal.

  - Android. Xiaomi Redmi 12C.

### VERSIONS USED
Cardboard XR Plugin 1.23.0
Unity 2022.3.5f1

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES2
   - [ X] OpenGL ES3
   - [ ] Metal

### SCREENSHOTS
Rendering
![imagen_2024-01-22_130600422](https://github.com/googlevr/cardboard/assets/151866198/b529e201-8859-4d36-8acc-c6ff937c6380)

Configuration
![image](https://github.com/googlevr/cardboard/assets/151866198/a00dfb3c-4381-40b1-85b1-25b095d2ba24)

XR Plug in
![image](https://github.com/googlevr/cardboard/assets/151866198/4cfc622d-a34c-41c5-bea4-eb63915b2526)

![image](https://github.com/googlevr/cardboard/assets/151866198/6885948d-32a6-4e06-96ac-cfc7aefadcb1)

![image](https://github.com/googlevr/cardboard/assets/151866198/d509a08b-6ba5-4112-9c69-5775e85aa052)

**Comment by lneumarkt** [comment]
Thank you for reaching out to us!

I noticed you selected the”Google AR Core” in the XR-Plugin Management, but “Cardboard XR Plugin” has to be selected. Could you please confirm if this solves the issue?

If this doesn’t solve your issue, could you please try testing the [sample scene](https://developers.google.com/cardboard/develop/unity/quickstart) to check if you experience the same behavior?

If this is not reproducible with the sample scene, we would need you to share with us a simple repro project where this issue is depicted, either via a zip file containing the Unity project or a link to a git repo. It would be of great help so as to be able to reproduce and solve this issue.

Thanks!

**Comment by IrvingMacias-Amco** [comment]
The problem was in the sample scene, maybe my phone doesn´t have gyroscope (I did some research on the topic, but I´m not entirely sure).
