### ISSUE TITLE
Video Pixelation in Google Cardboard VR Mode

### ISSUE THREAD

**Issue by Fasilkallot** [googlevr/cardboard#458]
When playing the video in Google Cardboard VR mode, pixelation is observed, particularly in dark areas of the video. However, when playing the same video in normal 360 mode, the video appears fine without any pixelation issues. This pixelation issue detracts from the immersive experience and affects the overall quality of VR playback.

### SMARTPHONE (please complete the following information):
- Device: Oneplus 8T
- OS
  - [ ] Android
- OS version 14

### EXPECTED BEHAVIOR
The video should maintain consistent quality in both normal 360 mode and Google Cardboard VR mode, without any noticeable pixelation or degradation in image quality.

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard XR Plugin 1.24.0

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
Example: 2023.2.3

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES3

### SCREENSHOTS

![Screenshot_2024-04-03-16-35-54-67_6db678231275f23f4e2fa72c692645be](https://github.com/googlevr/cardboard/assets/86238910/558e6d16-2d62-4b81-8cc0-a705b782a7c3)
![Screenshot_2024-04-03-16-36-00-91_6db678231275f23f4e2fa72c692645be](https://github.com/googlevr/cardboard/assets/86238910/0d71c0c4-c690-4330-8e93-cb1caa06d3b5)
![Screenshot_2024-04-03-16-36-08-66_6db678231275f23f4e2fa72c692645be](https://github.com/googlevr/cardboard/assets/86238910/9d0bcea8-afd7-4fb4-ae66-00748978122a)

**Comment by Mandelbrow** [comment]
Do you by "pixelation" mean the white dot in center of all of the views?
Isn't that something else in the scene, like a reticle perhaps?

**Comment by lneumarkt** [comment]
Thank you @Fasilkallot for reaching out.

We’ve tried to replicate the problem using different Android devices. But unfortunately we couldn’t reproduce the bug.

To help us identify and resolve this bug, I have a couple of questions for you:

- Could you please share some screenshots of the 360 images pointing to the same part of the world to visualize the difference between views?

- Could you please share your device's fingerprint?
   You can get it by running the following command in the terminal with the device connected to your computer.
   ```
   adb shell getprop ro.build.fingerprint
   ```
- Did you experiment the reported behavior on a different device?

- And lastly, could you please verify if the same behavior occurs with the Hello Cardboard sample app? You can follow the instructions on the [Quickstart for Unity](https://developers.google.com/cardboard/develop/unity/quickstart) to install the sample app.

If this is not reproducible with the sample scene, we would need you to share with us a simple repro project where this issue is depicted, either via a zip file containing the Unity project or a link to a git repo. It would be of great help so as to be able to reproduce and solve this issue.

Thanks!

**Comment by Fasilkallot** [comment]
Thank you for your response. While working on it, I was able to solve the issue by changing the rendering color space to Gamma.
