### ISSUE TITLE
Quickstart for Google Cardboard for Unity - Not Working

### ISSUE THREAD

**Issue by tadegiac** [googlevr/cardboard#77]
Hey Guys, i am a newbie in this field and i am working throgh an online Unity course. 
The VR-Chapter is from 2016. Therefore i tried the Google Quickstart tutorial.

Google Cardboard Quickstart:  https://developers.google.com/cardboard/develop/unity/quickstart

I've been trying for days to work through the tutorial, but i always get stuck at the same point. 
My Problem is the second last step (https://developers.google.com/cardboard/develop/unity/quickstart#xr_plug-in_management_settings_2) according to the manual i should be able to select "Cardboard XR Plugin" but this option is not shown at all. 

So under Project Settings -> XR Plug-in Management->Plug-in Providers i cant find "Cardboard XR Plugin" 
Does anyone know why?  
ps. I am really sorry if the question doesn't belong here, please let me know if that's the case. 
cheers

**Comment by jballoffet** [comment]
Because the course is from 2016, before the release of this Cardboard SDK, any reference you could find in it related to Cardboard may be outdated. As mentioned [here](https://developers.google.com/cardboard/develop/unity/quickstart#set_up_your_development_environment) the Cardboard XR Plugin requires Unity version 2019.3.12f1 or later. I’d recommend that you try the quickstart again while using that specific version of Unity if possible.

**Comment by sergiokoo** [comment]
Just exit Unity and then open the project again from Unity Hub, it will add the missed menu item.
